In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]
my_numpy = np.array(mylist)
my_numpy

array([1, 2, 3, 4])

In [3]:
type(my_numpy)

numpy.ndarray

In [5]:
arr1 = np.arange(1,20)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [6]:
arr1 = np.arange(1,20,3)
arr1

array([ 1,  4,  7, 10, 13, 16, 19])

In [10]:
arr1 = np.arange(1,101).reshape((10,10))
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
arr1 = np.zeros(3)
arr1

array([0., 0., 0.])

In [13]:
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr1 = np.ones(4)
arr1

array([1., 1., 1., 1.])

In [16]:
arr1 = np.ones((9,2))
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
arr1 = np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.seed(101)
np.random.randint(0,100,10)


array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
arr = np.arange(1,22).reshape(3,7)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [39]:
arr.max()

21

In [40]:
arr.argmax()

20

In [41]:
arr.min()

1

In [42]:
arr.argmin()

0

In [43]:
arr.sum()

231

In [44]:
arr.mean()

11.0

In [48]:
arr.shape

(3, 7)

In [55]:
arr = np.arange(0,100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
arr[3,3]

33

In [58]:
arr[:2,:2]

array([[ 0,  1],
       [10, 11]])

In [59]:
arr[1:2,:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [65]:
arr[:,3:4]

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83],
       [93]])

In [66]:
arr[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [69]:
arr[3,1:3]

array([31, 32])

In [74]:
arr[3:4,:] = -99
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [-99, -99, -99, -99, -99, -99, -99, -99, -99, -99],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [75]:
arr = np.random.randint(10,100,(3,5))
arr

array([[59, 93, 18, 39, 69],
       [44, 54, 82, 29, 20],
       [86, 97, 10, 83, 18]])

In [76]:
arr_copy = arr.copy()
arr_copy

array([[59, 93, 18, 39, 69],
       [44, 54, 82, 29, 20],
       [86, 97, 10, 83, 18]])

In [78]:
arr_copy[:,1] = 0
arr_copy

array([[59,  0, 18, 39, 69],
       [44,  0, 82, 29, 20],
       [86,  0, 10, 83, 18]])

In [79]:
arr

array([[59, 93, 18, 39, 69],
       [44, 54, 82, 29, 20],
       [86, 97, 10, 83, 18]])

['magma',
 'inferno',
 'plasma',
 'viridis',
 'cividis',
 'twilight',
 'twilight_shifted',
 'turbo',
 'Blues',
 'BrBG',
 'BuGn',
 'BuPu',
 'CMRmap',
 'GnBu',
 'Greens',
 'Greys',
 'OrRd',
 'Oranges',
 'PRGn',
 'PiYG',
 'PuBu',
 'PuBuGn',
 'PuOr',
 'PuRd',
 'Purples',
 'RdBu',
 'RdGy',
 'RdPu',
 'RdYlBu',
 'RdYlGn',
 'Reds',
 'Spectral',
 'Wistia',
 'YlGn',
 'YlGnBu',
 'YlOrBr',
 'YlOrRd',
 'afmhot',
 'autumn',
 'binary',
 'bone',
 'brg',
 'bwr',
 'cool',
 'coolwarm',
 'copper',
 'cubehelix',
 'flag',
 'gist_earth',
 'gist_gray',
 'gist_heat',
 'gist_ncar',
 'gist_rainbow',
 'gist_stern',
 'gist_yarg',
 'gnuplot',
 'gnuplot2',
 'gray',
 'hot',
 'hsv',
 'jet',
 'nipy_spectral',
 'ocean',
 'pink',
 'prism',
 'rainbow',
 'seismic',
 'spring',
 'summer',
 'terrain',
 'winter',
 'Accent',
 'Dark2',
 'Paired',
 'Pastel1',
 'Pastel2',
 'Set1',
 'Set2',
 'Set3',
 'tab10',
 'tab20',
 'tab20b',
 'tab20c',
 'grey',
 'gist_grey',
 'gist_yerg',
 'Grays',
 'magma_r',
 'inferno_r',
 'plasma_r',
 'viri